### ISSUE TITLE
As a dev, I need an environment and skeleton theme

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/dashboard#1]
## Overview
The whole point of handsfree.js is to do things handsfree. However, we'll still need an interface for organizing data, debugging, and making quick changes. So let's build one!

## Mockup
![793450b9-2f1f-4691-bf8b-b4e0067d9d1a](https://user-images.githubusercontent.com/42591975/45060728-1f15d280-b056-11e8-8195-77e070370e35.jpg)

## Tasks
- [x] Install and configure [vue-webpack](https://github.com/vuejs-templates/webpack)
- [x] Setup for working with Pug and Sass
- [x] Setup [Spectre.css](https://picturepan2.github.io/spectre/getting-started.html) for styles
- [x] Create the sidebar and two panel areas
- [x] Make it responsive
- [x] Build out the sidebar
- [x] Add Vuex
- [x] Load Handsfree
- [x] Create the "Handsfree Debugger" Panel
- [x] Change panels
- ...more planning needed

**Comment by labofoz** [comment]
Done! 

![image](https://user-images.githubusercontent.com/42591975/45188750-a09e6980-b1ea-11e8-984b-6c30965a8cb3.png)
