### ISSUE TITLE
As a user, I want to execute code

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/dashboard#3]
## Overview
Let's make the code block executable!

## Tasks
- [ ] When <kbd>Run</kbd> is clicked or "Shift+Entered" then `eval()` it
- [ ] Wrap in Try...Catches, and toast any error messages
- [ ] Hook into `console.log` and `console.error` and display this ourselves (so that users don't have to dig into dev consoles)
- [ ] Turn the "Status" light red on errors
- [ ] On errors, simply revert to the previous state
- [ ] Sandbox the code by running it inside an anonymous function (that way users can create local variables)
